color_palette:
  dark_bg_fore: "#D9D9D9"
  dark_bg_back: "#054062"
api:
  mapbox: pk.eyJ1IjoiZGN5Y2xlIiwiYSI6ImNrb2M2c3F1ajAxOXAycHRrb2Z6bXlxNTQifQ.TyU5SNPotu2hSZAJgm76wg
  mapbox_desc: Maisonvert Token on Dcycle mapbox account.
items:
  - title: My Cool Website
    baseurl: https://www.toutnaturelcaraibe.org/
    items_liste_partielle: 5
    lang: fr
    social:
      - name: facebook
        url: https://www.facebook.com/biodiversitepatrimoinenaturel/
    montrer_menaces: false
    home: /jekyll/jekyll.html
    menu:
      - id: home
        label: Home
        href: /jekyll/jekyll.html
