api:
  mapbox: pk.eyJ1IjoiZGN5Y2xlIiwiYSI6ImNrb2J3NGZzOTAxYnAycHFkbzkxbzlzZWYifQ.DdCrbOuTjU1z4Z-wi2NpNA
  mapbox_desc: Mapbox Dcycle
items:
  - baseurl: https://www.toutnaturelcaraibe.org/
    items_liste_partielle: 5
    social:
      - name: facebook
        url: https://www.facebook.com/biodiversitepatrimoinenaturel/
    montrer_menaces: false
