---
---
locale: 'fr'
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
backend:
  # See https://www.netlifycms.org/docs/authentication-backends/#github-backend
  name: github
  repo: maisonverte/maisonverte
  branch: master
  base_url: https://auth.static.dcycle.com
  auth_endpoint: auth/github/alberto56
media_folder: 'docs/media'
public_folder: "/media"
collections:
{% include netlifycms_config.html %}
{% include netlifycms_pages.html %}
{% include netlifycms_partenaires.html %}
  - name: "destinations"
    create: true
    label: "Destinations"
    folder: 'docs/destinations/_posts'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: "Destination (par exemple Haïti ou Sainte-Lucie)"
        name: nom
        widget: string
        required: true
      - label: "Points GPS du pays"
        hint: "Proviennent de https://raw.githubusercontent.com/datasets/geo-countries/master/data/countries.geojson"
        name: "latlon"
        widget: list
        fields:
          - label: "Lat, for example 51.500000"
            name: "lat"
            widget: string
            required: false
          - label: "Lon, for example -0.0900000"
            name: "lon"
            widget: string
            required: false
      - { label: 'layout', name: 'layout', widget: 'hidden', default: 'destination' }
      - label: 'Chemin SANS accents, SANS majuscules, avec une barre oblique avant et après (par exemple /haiti/ ou /sainte-lucie/)'
        name: 'permalink'
        widget: 'string'
        {% include netlifycms_validate_path.html %}
      - label: "Ordre dans la liste (-5 vient avant 1 vient avant 5 vient avant 5.2, par exemple)"
        name: order
        widget: number
        value_type: float
        required: false
  - name: "fiches"
    create: true
    label: "Fiches"
    folder: 'docs/fiches/_posts'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'fiche' }
      - label: 'Chemin SANS accents, SANS majuscules, avec une barre oblique avant et après (par exemple /haiti/etang-miragoane/)'
        name: 'permalink'
        widget: 'string'
        {% include netlifycms_validate_path.html %}
      - label: "Nom du lieu"
        name: nom
        widget: string
        required: true
      - label: "Destination (par exemple Haïti ou Sainte-Lucie)"
        name: destination
        widget: string
        required: false
      - label: "Sous-titre"
        name: soustitre
        widget: string
        required: false
      - label: "Ordre dans la liste (-5 vient avant 1 vient avant 5 vient avant 5.2, par exemple)"
        name: order
        widget: number
        value_type: float
        required: false
      - label: "Images"
        name: "img"
        widget: "list"
        required: false
        fields:
          - {label: "image", name: img, widget: image, required: false}
          - {label: "décrivez cette image pour les personnes non-voyantes", name: alt, widget: string, required: false}
      - label: "Géolocalisation (itinéraire GPS)"
        name: geolocalisation
        widget: string
        required: false
      - label: "Description"
        name: description
        widget: text
        required: false
      - label: "Sa biodiversité (son écosystème)"
        name: biodiversite
        widget: text
        required: false
      - label: "Ses potentialités écotouristiques"
        name: potentialites
        widget: text
        required: false
      - label: "Ses menaces par rapport aux changements climatiques et les mesures à prendre pour s’adapter aux aléas naturels"
        name: menaces
        widget: text
        required: false
  - name: "articles"
    create: true
    label: "Articles"
    folder: 'docs/articles/_posts'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'sharable' }
      - label: "Titre"
        name: title
        widget: string
        required: true
      - label: "Corps"
        name: body
        widget: markdown
        required: false
