# config.yml

locale: 'fr'
backend:
  # See https://www.netlifycms.org/docs/authentication-backends/#github-backend
  name: github
  repo: maisonverte/maisonverte
  branch: master
  base_url: https://auth.static.dcycle.com
  auth_endpoint: auth/github/alberto56
media_folder: 'docs/media'
public_folder: "/media"
collections:
  - name: "fiches"
    label: "fiches"
    editor:
      preview: false
    files:
      - label: "fiches"
        name: 'fiches'
        file: 'docs/_data/fiches.yml'
        fields:
          - label: "Fiches"
            name: "items"
            widget: "list"
            fields:
              - label: "Nom du lieu"
                name: nom
                widget: string
                required: false
              - label: "Images"
                name: "img"
                widget: "list"
                required: false
                fields:
                  - {label: "image", name: img, widget: image, required: false}
                  - {label: "décrivez cette image pour les personnes non-voyantes", name: alt, widget: string, required: false}
              - label: "Géolocalisation (itinéraire GPS)"
                name: geolocalisation
                widget: string
                required: false
              - label: "Description"
                name: description
                widget: text
                required: false
              - label: "Sa biodiversité (son écosystème)"
                name: biodiversite
                widget: text
                required: false
              - label: "Ses potentialités écotouristiques"
                name: potentialites
                widget: text
                required: false
              - label: "Ses menaces par rapport aux changements climatiques et les mesures à prendre pour s’adapter aux aléas naturels"
                name: menaces
                widget: text
                required: false
